USE team03;

DROP TABLE IF EXISTS `Bookmark`;
DROP TABLE IF EXISTS `Review`;
DROP TABLE IF EXISTS `Menu`;
DROP TABLE IF EXISTS `Closed_Days`;
DROP TABLE IF EXISTS `Restaurant`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Category`;
DROP TABLE IF EXISTS `Region`;
